- name: var playbook
  hosts: nginx
  vars:
    DATE: 30.05.20025
    MESSAGE: "How are you"
  task:
    - name: print the variables
      ansible.builtin.debug:
        msg: "Today is {{ DATE }}, {{ MESSAGE }}"
      