- name: This is the program for all variables
  hosts: mongodb
  vars_files: 
    - vars.yaml

  vars_prompt:
    - name: LOCATION
      prompt: "Entre prompt!"
  vars:
    LOCATION: This is from playbook
  tasks:
    - name: print the varialbe 
      ansible.builtin.debug:
        msg:  This is 1.{{ LOCATION }}

    - name: print the variable
      vars: 
        LOCATION: This is from within the task
      ansible.builtin.debug:
        msg: This is 2. {{ LOCATION }}

- name: Playbook 2
  hosts: mongodb
  vars_file:
    - vars.yaml
  tasks:
    - name: print the variable
      ansible.builtin.debug:
      msg: This from {{ LOCATION }}
      
    
  