- name: varible through prompt
  hosts: mongodb
  vars_prompt:
    - name: USER_NAME
      prompt: Enter your User name
      private: no
    - req: REQUIREMENT
      prompt: Enter yuor requirement?
  tasks:
    - name: printing prompts
      ansible.builtin.debug:
        msg: "Hello {{ USER_NAME }} youu requirement is {{ REQUIREMENT }}"