- name: Inventory variables
  hosts: mongodb
  tasks: 
  - name: print host level variable
    ansible.builtin.debug:
      msg: "Hi This {{ ansible_user }}, {{ LOCATION }} {{ anisble_password }}"



# - name: Local variables
#   hosts: local
#   connection: local
#   tasks: 
#   - name: print host level variable
#     ansible.builtin.debug:
#       msg: "Hi This {{ LOCATION }} "