- name: installing multiple software in loop
  hosts: mongodb
  become: yes
  tasks:
    - name: program logic
      ansible.builtin.debug:
        msg: "{{ name.item }}"
        msg: "{{ state.item }}"
      loop:
        - { name: 'nginx', state: 'installed' }
        - { name: 'mysql' , state: 'remove'  }
        - { name: 'httpd' , state: 'instatted' }