- name: updating multiple packages 
  hosts: mongodb
  tasks:
  - name: using loop to install/remove packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mongodb', state: 'remove' }
    - { name: 'mysql', state: 'present' }
    - { name: 'httpd', state: 'absent' }