- name: installing multiple software in loop
  hosts: mongodb
  become: yes
  tasks:
  - name: program logic
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'installed' }
    - { name: 'mysql' , state: 'remove'  }
    - { name: 'httpd' , state: 'installed' }