- name: multi package installation
  hosts: mongodb
  become: yes
  tasks:
  - name: loop and package installation
    ansible.builtin.packages:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'absent' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'httpd', state: 'absent' }
    - { name: 'mongodb', state: 'absent'}