- name: Juice_Stall
  hosts: local
  connection: local
  vars_prompt:
    name: UNAME 
    prompt: "Enter your name: "
  vars_files: fruits.yaml
  tasks: 
    - name: welcome message
      ansible.builtin.debug:
        msg: "Hi Welcome {{UNAME}} to Kishore's Fruits Stall"
  
  # tasks: 
  #   - name: " Selection of juice "
  #     ansible.builtin.debug:
  #       msg: " what do you want today, {{ FRUITS }}
  #     vars_prompt:

  tasks: 
    - name: welcome message
      ansible.builtin.debug:
        msg: "Hi Welcome "
  