- name: Juice_Stall
  hosts: local
  connection: local
  vars_files: fruits.yaml
  # tasks:
  # - name: welcome message
  #   ansible.builtin.debug:
  #     msg: "Hi Welcome to Kishores' Fruits Stall"
  vars_prompt:
  - name: UNAME 
    prompt: "Hi Welcome to Kishore's Fruits Stall Enter your name "
    private: no
  - name: SELECTION 
    prompt: " Which fruit do you want {{ FRUITS }}..? Enter numbers 1 - 5"
    private: no

  - name: Type
    prompt: " How do you want it {{ TYPE }} ? "
    private: no

  tasks: 
  - name: welcome message
    ansible.builtin.debug:
      msg: " Hi {{ UNAME }} - Here is your order {{ SELECTION }} of {{ TYPE }} \n Quantity is {{ QUANTITY }} Cost is {{ RATE }}"
    when:
      " FRUITS | int = 1 "

  # - name: Juice or cut fruits
  #   tasks:
  - name: " Selection of juice "
    ansible.builtin.debug:
      msg: " what do you want today, {{ FRUITS }}"

    

  