- name: Juice_Stall
  hosts: local
  connection: local
  vars_files: fruits.yaml
  tasks:
  - name: welcome message
    ansible.builtin.debug:
      msg: Hi Welcome to Kishores' Fruits
  vars_prompt:
  - name: UNAME 
    prompt: "Enter your name "
    private: no
  - name: SELECTION 
    prompt: " Which fruit do you want {{ FRUITS }}..? "
    private: no

  - name: Type
    prompt: " How do you want it {{ TYPE }} ? "
    private: no

  tasks: 
  - name: welcome message
    ansible.builtin.debug:
      msg: "Hi Welcome {{UNAME}} to Kishore's Fruits Stall {{ FRUITS }}"

  # - name: Juice or cut fruits
  #   tasks:
  - name: " Selection of juice "
    ansible.builtin.debug:
      msg: " what do you want today, {{ FRUITS }}"

    

  