- name: Juice_Stall
  hosts: local
  connection: local
  vars_prompt:
  - name: UNAME 
    prompt: "Enter your name: "
    private: no
  - name: SELECTION 
    prompt: " What is your selection {{ FRUITS }}..."
    private: no

  vars_files: fruits.yaml
  tasks: 
  - name: welcome message
    ansible.builtin.debug:
      msg: "Hi Welcome {{UNAME}} to Kishore's Fruits Stall {{ FRUITS }}"

  # - name: Juice or cut fruits
  #   tasks:
  - name: " Selection of juice "
    ansible.builtin.debug:
      msg: " what do you want today, {{ FRUITS }}"
    

  