- name: install nginx
  hosts: local
  connections: local
  tasks:
  - name: installing nginx via dnf
    ansible.builtin.dnf:
      name: nginx
      state: present
    when:
      ansible_os_family == "Redhat"

  - name: using apt to install if os is debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when:
      ansible_os_family == "Debian"