- name: Shell and command module
  hosts: local
  connection: local
  tasks:
  - name: commmand module
    ansible.builtin.shell:
      ls -ltr > /tmp/shell.txt
  
  - name: shell module
    ansible.builtin.command:
      ls -ltr
    