- name: Shell and command module
  hosts: local
  connection: local
  tasks:
  - name: commmand module
    ansible.builtin.shell:
      ls -ltr >> /tmp/shell.txt
    register: result
  - name: view result
    ansible.builtin.debug:
      msg: "{{ result }}"
  
  - name: command module
    ansible.builtin.command:
      ls -ltr 
    register: command_output

  - name: view result2
    ansible.builtin.debug:
      msg: "{{ command_output }}"
