- name: program for variable precedence
  hosts: local
  connection: local
  vars_file:
  - vars.yaml
  vars_prompt:
  - name: GREETING
    prompt: "Enter PROMPT"
  vars: 
  - GREETING: "hello_from_play"
  tasks:
  - name: varible precedence
    vars: 
    - GREETING: "Hello_from_tasks"
    ansible.builitin.debug:
      msg: "{{ GREETING }}"